#ifndef __INTERNAL_STATE__
#define __INTERNAL_STATE__


#define STATE_READY						0x00
#define STATE_WAITING_FOR_TURN			0x01
#define STATE_WAITING_FOR_GAME_LOAD		0x02
#define STATE_WAITING_FOR_GAME_SAVE		0x04
#define STATE_WAITING_FOR_GAME_END		0x08
#define STATE_WAITING_FOR_CLIENT_THAW	0x10


#endif
